### ISSUE TITLE
pattern start/stop quantize

### ISSUE THREAD

**Issue by tehn** [tehn/mlr#15]
pattern start/stop should be quantized if quantize is turned on

**Comment by polyoptics** [comment]
Hoping this would mean you could record a quantized chunk (x amount of beats/bars or w/e) but the content in the chunk could still be unquantized. Then the playback of that chunk could be quantized for start/stop/looping.

**Comment by tehn** [comment]
this is a can of worms, thanks for the suggestion.

seems like there needs to be a quantize config option/window where you can define what gets quantized.

**Comment by kasselvania** [comment]
It would seem that once you look in to quantizing, there needs to be ways to define bars, beats, start and stop before bringing it all in. This would open a lot of doors with using the program In new ways (live drums, etc) but it could complicate the program and make the programming much more complex.
