### ISSUE TITLE
When loading clips only stop track playback if a new clip is actually selected

### ISSUE THREAD

**Issue by etherbrooklyn** [tehn/mlr#18]
For discussion and consideration.

Current behaviour is to immediately stop track playback when KEY2 is pressed, with no way to cancel and leave track playing (e.g. if KEY2 was mistakenly pressed).

Better behaviour would be to only stop track if KEY2 is pressed, then a valid audio file actually selected and successfully loaded into the relevant buffer.

**Comment by tehn** [comment]
this description is a little off, but i fixed the problem.

clips were stopped on clip position select, even if you re-selected the existing position.
works more as expected now. updated.

6b55718..1e52477
